FROM python:3.11-slim

WORKDIR /opt/etl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY etl.py .
COPY config.yml .

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/opt/etl/etl.py"]
